# this build is designed to replicate the Travis CI workflow
name: Build with Maven

on:
  push:
    branches: [ "CQL" ]
  pull_request:
    branches: [ "CQL" ]

jobs:
  java-11:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn clean install --file pom.xml

  java-17:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn clean install --file pom.xml
